### ISSUE TITLE
feat/

### ISSUE THREAD

**Issue by LeenDrew** [LeenDrew/si-parser-client#1]
## Tasks:
- [ ] Лоадер при ожидании ответа сервера
- [ ] Показывать полученный файл в списке
- [ ] Показывать ошибки алертом
- [ ] Cleanup
### After:
